### ISSUE TITLE
Feedbacks Demo Partner Vault

### ISSUE THREAD

**Issue by EllynBsc** [FiligranHQ/xtm-hub#71]
### Todos

- [x] logout, redirect to /

**As an admin platform/admin orga/user, in the partner vault**

- [x] @hervyt add ‘number of download’ in the table (last column)
- [x] @hervyt Align 'icon' at the end all the way to the right
- [x] @hervyt Put the most recent documents first
- [x] @hervyt  Reorder the column in the following order: name, description date, nb of download, icon manage
- [x] @hervyt If no available service, do not display anything / remove the statement 'service available, you don' hav

**As an admin platform in the partner vault**

- [x] @hervyt Replace 'Add organisation' by 'Subscribe organization'

- [x] @hervyt  Replace toaster wording with 'You've already subscribed this organization to this service' instead of 'You have already subscribed this service.
- [x] @hervyt  Be able to navigate to service partner vault via settings to add documents with a button 'Add documents' at the end of a service row 
![Image](https://github.com/user-attachments/assets/8e3c14fb-0ea3-4bdf-ada0-7cd783534815)

- [x] @hervyt when I delete a document in the vault: I have a 'remover_id' column in the database, and the document isn't actually deleted (it just becomes inactive)."
- [x] @hervyt warning confirmation for destroy actions: on deleting a document and on removing subscription from organisation
